/**
 * Sync Config Service
 * Manages OPMS-to-NetSuite sync enable/disable state in database
 * 
 * IMPORTANT: This is the ONLY way to control sync operations.
 * The OPMS_SYNC_ENABLED environment variable is IGNORED.
 * 
 * Sync control methods:
 * 1. Dashboard toggle (/api/sync-dashboard/)
 * 2. API endpoints: POST /api/opms-sync/enable, POST /api/opms-sync/disable
 * 3. Direct database: UPDATE netsuite_opms_sync_config SET config_value = 'false'
 */

const logger = require('../utils/logger');
const db = require('../config/database');

class SyncConfigService {
    constructor() {
        this.configKey = 'opms_sync_enabled';
        // Additional feature flags (separate manual single-item controls)
        // New canonical keys
        this.manualItemDashboardKey = 'opms_sync_manual_single_item_dashboard_enabled';
        this.manualItemItemIndexKey = 'opms_sync_manual_single_item_colorline_list_enabled';
        // Legacy keys for backward compatibility/migration
        this.legacyKeys = {
            [this.manualItemDashboardKey]: 'opms_manual_item_sync_dashboard_enabled',
            [this.manualItemItemIndexKey]: 'opms_manual_item_sync_item_index_enabled'
        };
        // Dry-run: use production NetSuite environment override (boolean toggle)
        this.dryRunUseProdKey = 'opms_dryrun_use_netsuite_prod';
        this.configTable = 'netsuite_opms_sync_config';
    }

    /**
     * Check if sync is enabled
     * 
     * IMPORTANT: This is the ONLY source of truth for sync enabled state.
     * Environment variables are IGNORED. All sync operations check this method.
     * 
     * @returns {Promise<boolean>}
     */
    async isSyncEnabled() {
        try {
            const query = `
                SELECT config_value 
                FROM ${this.configTable}
                WHERE config_key = ?
                LIMIT 1
            `;
            
            const [rows] = await db.query(query, [this.configKey]);
            
            if (!rows || rows.length === 0) {
                // Default to enabled if no config exists
                logger.info('No sync config found, defaulting to enabled');
                await this.enableSync(false); // Set default without logging
                return true;
            }
            
            const enabled = rows[0].config_value === 'true';
            return enabled;
        } catch (error) {
            logger.error('Failed to check sync enabled status', {
                error: error.message,
                configKey: this.configKey
            });
            // Default to enabled on error
            return true;
        }
    }

    /**
     * Generic feature flag checker with default
     * @param {string} key
     * @param {boolean} defaultValue
     * @returns {Promise<boolean>}
     */
    async isFeatureEnabled(key, defaultValue = true) {
        try {
            const legacyKey = this.legacyKeys[key];
            let rows;
            if (legacyKey) {
                const query = `
                    SELECT config_key, config_value 
                    FROM ${this.configTable}
                    WHERE config_key IN (?, ?)
                `;
                const [res] = await db.query(query, [key, legacyKey]);
                rows = res;
            } else {
                const query = `
                    SELECT config_key, config_value 
                    FROM ${this.configTable}
                    WHERE config_key = ?
                    LIMIT 1
                `;
                const [res] = await db.query(query, [key]);
                rows = res;
            }

            if (!rows || rows.length === 0) {
                // Initialize with default
                await this.setFeature(key, defaultValue, 'Feature flag autogenerated with default');
                return defaultValue;
            }

            // Prefer new key; if only legacy present, migrate
            const newRow = rows.find(r => r.config_key === key);
            if (newRow) {
                return newRow.config_value === 'true';
            }

            const legacyRow = rows.find(r => legacyKey && r.config_key === legacyKey);
            if (legacyRow) {
                const enabled = legacyRow.config_value === 'true';
                // Migrate to new key (keep legacy intact)
                await this.setFeature(
                    key,
                    enabled,
                    `Renamed from ${legacyKey} on first read`
                );
                return enabled;
            }

            // Fallback
            await this.setFeature(key, defaultValue, 'Feature flag autogenerated with default');
            return defaultValue;
        } catch (error) {
            logger.error('Failed to check feature flag', { key, error: error.message });
            return defaultValue;
        }
    }

    /**
     * Set feature flag (insert or update)
     * @param {string} key
     * @param {boolean} enabled
     * @param {string} description
     */
    async setFeature(key, enabled, description = null) {
        const value = enabled ? 'true' : 'false';
        const desc = description || `Feature flag ${key}`;
        const query = `
            INSERT INTO ${this.configTable} (config_key, config_value, description)
            VALUES (?, ?, ?)
            ON DUPLICATE KEY UPDATE 
                config_value = VALUES(config_value),
                description = COALESCE(VALUES(description), description),
                updated_at = NOW()
        `;
        await db.query(query, [key, value, desc]);
        return enabled;
    }

    /**
     * Enable sync
     * @returns {Promise<boolean>}
     */
    async enableSync(logAction = true) {
        try {
            const query = `
                INSERT INTO ${this.configTable} (config_key, config_value, description)
                VALUES (?, 'true', 'Controls OPMS-to-NetSuite sync (true=enabled, false=disabled)')
                ON DUPLICATE KEY UPDATE 
                    config_value = 'true',
                    updated_at = NOW()
            `;
            
            await db.query(query, [this.configKey]);
            
            if (logAction) {
                logger.info('🔓 OPMS-to-NetSuite sync ENABLED');
            }
            
            return true;
        } catch (error) {
            logger.error('Failed to enable sync', {
                error: error.message,
                configKey: this.configKey
            });
            throw error;
        }
    }

    /**
     * Disable sync
     * @returns {Promise<boolean>}
     */
    async disableSync(logAction = true) {
        try {
            const query = `
                INSERT INTO ${this.configTable} (config_key, config_value, description)
                VALUES (?, 'false', 'Controls OPMS-to-NetSuite sync (true=enabled, false=disabled)')
                ON DUPLICATE KEY UPDATE 
                    config_value = 'false',
                    updated_at = NOW()
            `;
            
            await db.query(query, [this.configKey]);
            
            if (logAction) {
                logger.info('🔒 OPMS-to-NetSuite sync DISABLED');
            }
            
            return false;
        } catch (error) {
            logger.error('Failed to disable sync', {
                error: error.message,
                configKey: this.configKey
            });
            throw error;
        }
    }

    /**
     * Get sync configuration
     * @returns {Promise<object>}
     */
    async getSyncConfig() {
        try {
            // Use helpers to ensure migration/defaults
            const globalEnabled = await this.isSyncEnabled();
            const manualDashEnabled = await this.isManualItemDashboardEnabled();
            const manualItemIndexEnabled = await this.isManualItemItemIndexEnabled();
            const dryRunUseProd = await this.isDryRunUseProdEnabled();

            return {
                enabled: globalEnabled,
                manualItemDashboardEnabled: manualDashEnabled,
                manualItemItemIndexEnabled: manualItemIndexEnabled,
                dryRunUseProduction: dryRunUseProd,
                keys: {
                    global: this.configKey,
                    manualItemDashboard: this.manualItemDashboardKey,
                    manualItemItemIndex: this.manualItemItemIndexKey,
                    dryRunUseProd: this.dryRunUseProdKey
                }
            };
        } catch (error) {
            logger.error('Failed to get sync config', {
                error: error.message,
                configKey: this.configKey
            });
            throw error;
        }
    }

    /**
     * Toggle sync state
     * @returns {Promise<boolean>} New state (true=enabled, false=disabled)
     */
    async toggleSync() {
        try {
            const currentState = await this.isSyncEnabled();
            const newState = !currentState;
            
            if (newState) {
                await this.enableSync();
            } else {
                await this.disableSync();
            }
            
            logger.info(`🔄 Sync state toggled to: ${newState ? 'ENABLED' : 'DISABLED'}`);
            
            return newState;
        } catch (error) {
            logger.error('Failed to toggle sync', {
                error: error.message
            });
            throw error;
        }
    }

    // Convenience wrappers for the two new flags
    async isManualItemDashboardEnabled() {
        return this.isFeatureEnabled(this.manualItemDashboardKey, true);
    }

    async enableManualItemDashboard() {
        logger.info('🔓 Manual single-item sync (Dashboard) ENABLED');
        return this.setFeature(
            this.manualItemDashboardKey,
            true,
            'Controls manual single-item sync on /api/sync-dashboard (UI)'
        );
    }

    async disableManualItemDashboard() {
        logger.info('🔒 Manual single-item sync (Dashboard) DISABLED');
        return this.setFeature(
            this.manualItemDashboardKey,
            false,
            'Controls manual single-item sync on /api/sync-dashboard (UI)'
        );
    }

    async isManualItemItemIndexEnabled() {
        return this.isFeatureEnabled(this.manualItemItemIndexKey, true);
    }

    async enableManualItemItemIndex() {
        logger.info('🔓 Manual single-item sync (Colorline List) ENABLED');
        return this.setFeature(
            this.manualItemItemIndexKey,
            true,
            'Controls manual single-item sync button at Colorline list (/item/index)'
        );
    }

    async disableManualItemItemIndex() {
        logger.info('🔒 Manual single-item sync (Colorline List) DISABLED');
        return this.setFeature(
            this.manualItemItemIndexKey,
            false,
            'Controls manual single-item sync button at Colorline list (/item/index)'
        );
    }

    // Dry-run environment toggle helpers
    async isDryRunUseProdEnabled() {
        return this.isFeatureEnabled(this.dryRunUseProdKey, false);
    }

    async enableDryRunUseProd() {
        logger.info('🧪 Dry-Run NetSuite environment override: PRODUCTION');
        return this.setFeature(
            this.dryRunUseProdKey,
            true,
            'When true, dry-run operations prefer NetSuite PRODUCTION configuration'
        );
    }

    async disableDryRunUseProd() {
        logger.info('🧪 Dry-Run NetSuite environment override: SANDBOX');
        return this.setFeature(
            this.dryRunUseProdKey,
            false,
            'When false, dry-run operations prefer NetSuite SANDBOX configuration'
        );
    }
}

module.exports = new SyncConfigService();

